apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "air-quality-predictor"
        static_configs:
          - targets: ["air-quality-service:8000"]
